// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggojmfbpsqzcyazwnibd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnb2ptZmJwc3F6Y3lhenduaWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDIwNTEsImV4cCI6MjA2ODUxODA1MX0.1Q7rWqqg3REYUI7pqT36hJXkKbO2njS3ZhVpvtHWaKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});